variables:
  PROJECT_NAME: Teleport
  IMAGE_TAG: js910924/teleport
  HEROKU_IMAGE_TAG: registry.heroku.com/teleport-target/web
  HEROKU_API_KEY: ade0fb23-b2b0-497b-a614-1c58a53ee962

stages:
  - build
  - test
  - staging

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  script:
    - echo "$VERSION" > ./$PROJECT_NAME/wwwroot/version.txt
    - dotnet build

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  script:
    - dotnet test

staging:
  stage: staging
  image: docker:latest
  services:
    - docker:dind
  script:
    # - docker login -u "${DOCKERHUB_USER}" --password=${DOCKERHUB_PASSWORD}
    # - docker build -t $IMAGE_TAG .
    # - docker push $IMAGE_TAG
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker build -t $HEROKU_IMAGE_TAG .
    - docker push $HEROKU_IMAGE_TAG
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY dickeyxxx/heroku-cli heroku container:release web --app teleport-target