image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim

before_script:
  - "dotnet restore"

stages:
  - build
  - test

build:
  stage: build
  script:
    - "dotnet build --no-restore"

test:
  stage: test
  script:
    - "dotnet test --no-restore"
