image: microsoft/dotnet:latest

before_script:
  - "dotnet restore"

stages:
  - build
  - test

build:
  stage: build
  script:
    - "dotnet build --no-restore"

test:
  stage: test
  script:
    - "dotnet test --no-restore"