variables:
  PROJECT_NAME: Teleport
  IMAGE_TAG: js910924/teleport

stages:
  - build
  - test
  - staging

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  script:
    - echo "$VERSION" > ./$PROJECT_NAME/wwwroot/version.txt
    - dotnet build

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  script:
    - dotnet test

staging:
  stage: staging
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "${DOCKERHUB_USER}" --password=${DOCKERHUB_PASSWORD}
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG